/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppGigsIndexRouteImport } from './routes/_app/gigs/index'
import { Route as AppMessagesSellerIdRouteImport } from './routes/_app/messages/$sellerId'
import { Route as AppGigsNewRouteImport } from './routes/_app/gigs/new'
import { Route as AppGigsManageRouteImport } from './routes/_app/gigs/manage'
import { Route as AppGigsGigIdRouteImport } from './routes/_app/gigs/$gigId'
import { Route as AppGigsGigIdHireRouteImport } from './routes/_app/gigs/$gigId/hire'
import { Route as AppGigsGigIdEditRouteImport } from './routes/_app/gigs/$gigId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsIndexRoute = AppGigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesSellerIdRoute = AppMessagesSellerIdRouteImport.update({
  id: '/messages/$sellerId',
  path: '/messages/$sellerId',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsNewRoute = AppGigsNewRouteImport.update({
  id: '/gigs/new',
  path: '/gigs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsManageRoute = AppGigsManageRouteImport.update({
  id: '/gigs/manage',
  path: '/gigs/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsGigIdRoute = AppGigsGigIdRouteImport.update({
  id: '/gigs/$gigId',
  path: '/gigs/$gigId',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsGigIdHireRoute = AppGigsGigIdHireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => AppGigsGigIdRoute,
} as any)
const AppGigsGigIdEditRoute = AppGigsGigIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppGigsGigIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/gigs/$gigId': typeof AppGigsGigIdRouteWithChildren
  '/gigs/manage': typeof AppGigsManageRoute
  '/gigs/new': typeof AppGigsNewRoute
  '/messages/$sellerId': typeof AppMessagesSellerIdRoute
  '/gigs/': typeof AppGigsIndexRoute
  '/gigs/$gigId/edit': typeof AppGigsGigIdEditRoute
  '/gigs/$gigId/hire': typeof AppGigsGigIdHireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/gigs/$gigId': typeof AppGigsGigIdRouteWithChildren
  '/gigs/manage': typeof AppGigsManageRoute
  '/gigs/new': typeof AppGigsNewRoute
  '/messages/$sellerId': typeof AppMessagesSellerIdRoute
  '/gigs': typeof AppGigsIndexRoute
  '/gigs/$gigId/edit': typeof AppGigsGigIdEditRoute
  '/gigs/$gigId/hire': typeof AppGigsGigIdHireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/gigs/$gigId': typeof AppGigsGigIdRouteWithChildren
  '/_app/gigs/manage': typeof AppGigsManageRoute
  '/_app/gigs/new': typeof AppGigsNewRoute
  '/_app/messages/$sellerId': typeof AppMessagesSellerIdRoute
  '/_app/gigs/': typeof AppGigsIndexRoute
  '/_app/gigs/$gigId/edit': typeof AppGigsGigIdEditRoute
  '/_app/gigs/$gigId/hire': typeof AppGigsGigIdHireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/wallet'
    | '/gigs/$gigId'
    | '/gigs/manage'
    | '/gigs/new'
    | '/messages/$sellerId'
    | '/gigs/'
    | '/gigs/$gigId/edit'
    | '/gigs/$gigId/hire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/wallet'
    | '/gigs/$gigId'
    | '/gigs/manage'
    | '/gigs/new'
    | '/messages/$sellerId'
    | '/gigs'
    | '/gigs/$gigId/edit'
    | '/gigs/$gigId/hire'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/wallet'
    | '/_app/gigs/$gigId'
    | '/_app/gigs/manage'
    | '/_app/gigs/new'
    | '/_app/messages/$sellerId'
    | '/_app/gigs/'
    | '/_app/gigs/$gigId/edit'
    | '/_app/gigs/$gigId/hire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/': {
      id: '/_app/gigs/'
      path: '/gigs'
      fullPath: '/gigs/'
      preLoaderRoute: typeof AppGigsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$sellerId': {
      id: '/_app/messages/$sellerId'
      path: '/messages/$sellerId'
      fullPath: '/messages/$sellerId'
      preLoaderRoute: typeof AppMessagesSellerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/new': {
      id: '/_app/gigs/new'
      path: '/gigs/new'
      fullPath: '/gigs/new'
      preLoaderRoute: typeof AppGigsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/manage': {
      id: '/_app/gigs/manage'
      path: '/gigs/manage'
      fullPath: '/gigs/manage'
      preLoaderRoute: typeof AppGigsManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/$gigId': {
      id: '/_app/gigs/$gigId'
      path: '/gigs/$gigId'
      fullPath: '/gigs/$gigId'
      preLoaderRoute: typeof AppGigsGigIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/$gigId/hire': {
      id: '/_app/gigs/$gigId/hire'
      path: '/hire'
      fullPath: '/gigs/$gigId/hire'
      preLoaderRoute: typeof AppGigsGigIdHireRouteImport
      parentRoute: typeof AppGigsGigIdRoute
    }
    '/_app/gigs/$gigId/edit': {
      id: '/_app/gigs/$gigId/edit'
      path: '/edit'
      fullPath: '/gigs/$gigId/edit'
      preLoaderRoute: typeof AppGigsGigIdEditRouteImport
      parentRoute: typeof AppGigsGigIdRoute
    }
  }
}

interface AppGigsGigIdRouteChildren {
  AppGigsGigIdEditRoute: typeof AppGigsGigIdEditRoute
  AppGigsGigIdHireRoute: typeof AppGigsGigIdHireRoute
}

const AppGigsGigIdRouteChildren: AppGigsGigIdRouteChildren = {
  AppGigsGigIdEditRoute: AppGigsGigIdEditRoute,
  AppGigsGigIdHireRoute: AppGigsGigIdHireRoute,
}

const AppGigsGigIdRouteWithChildren = AppGigsGigIdRoute._addFileChildren(
  AppGigsGigIdRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWalletRoute: typeof AppWalletRoute
  AppGigsGigIdRoute: typeof AppGigsGigIdRouteWithChildren
  AppGigsManageRoute: typeof AppGigsManageRoute
  AppGigsNewRoute: typeof AppGigsNewRoute
  AppMessagesSellerIdRoute: typeof AppMessagesSellerIdRoute
  AppGigsIndexRoute: typeof AppGigsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppWalletRoute: AppWalletRoute,
  AppGigsGigIdRoute: AppGigsGigIdRouteWithChildren,
  AppGigsManageRoute: AppGigsManageRoute,
  AppGigsNewRoute: AppGigsNewRoute,
  AppMessagesSellerIdRoute: AppMessagesSellerIdRoute,
  AppGigsIndexRoute: AppGigsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
